name = input("what is your name?" )
print("hellow " + name)
number = input("what is your phone number?" )
print("thank you " + name)
count = input("what is your country?" )
print("thank you " + name)
email = input("Email" )
print("thank you " + name)
code = ("github.com/firaolt/")
print(" this is my github channal "  +  code  + " thank you!! " + " by by " + name)
